### ISSUE TITLE
add dropdown for location type on person page

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#129]
currently all location types are shown as Districts

**Comment by rausch-supola** [comment]
currently all location types are shown as Districts

**Comment by kisram** [comment]
just realised that this causes a challenge for the synchronization with the table
e.g. what category is displayed when all location types are displayed in the table?

**Comment by kisram** [comment]
and I also just realized that the chart isn't showing all locations as districts, but only districts. I think there's a misunderstanding about the data here. Some locations that were previously districts were moved to other catgories, but only in the Documents table

**Comment by kisram** [comment]
We could still add the dropdown. That would mean that the basis for the calculations would change: choose location type from dropdown -> draw chart based on the active rows and the column corresponding to the location type selected
