### ISSUE TITLE
create basic list/detail view for Neighborhood

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#13]
* create a template for the listview (see e.g. templates/static/documents.j2)
* create a template for detail view (see. e.g. templates/district.j2)

adapt `build.py` to render those templates with data from `html/json_dumps/neighbourhoods.json`

**Comment by kisram** [comment]
Spent a lot of time figuring out why certain things didn't work on Windows, then created the templates for the neighborhoods based on the districts.
