### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#162]
clicking on person on locations page not working. It seems, it's only locally, on https://grocerist.github.io/ it's working

**Comment by kisram** [comment]
Can't reproduce this, but this was [an issue](https://github.com/grocerist/grocerist-app/issues/157) before, maybe you don't have [the fix](https://github.com/grocerist/grocerist-app/commit/715a41cba7c86a3b7f1d8cdb80a2434b0d9e90f4) yet locally?

**Comment by rausch-supola** [comment]
Yes, since the fix was on May 8 and the branch 155 was opened on May 7, this would be the cause. Today it's working on the main branch, I guess it was a caching issue yesterday
