### ISSUE TITLE
imprint

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#179]
since we build the page every day and our services are down, the Imprint page looks like this:
![image](https://github.com/user-attachments/assets/de1dd23b-1c66-48a4-9951-fa9daf4ac251)
@csae8092 do we have an existing solution where if the service is unavailable, the previous version is used?

**Comment by csae8092** [comment]
@kisram 
good point! in another project I did this
https://github.com/jerusalem-70-ad/jad-python-static/commit/7ac1cf9e89020364ac94d644fc6d02548b610274#diff-c2cbb0126cbadb86b309223fafc6c104f2d558773531e8bf2e39c85616e1e9a2
