### ISSUE TITLE
markers on detail pages

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#193]
adjust the markers on the goods and locations(?) detail pages
@rausch-supola should we keep the locations markers as circleMarkers or use the new markers (with a different icon) as well?

**Comment by rausch-supola** [comment]
I am also ok with an icon marker, but till now the size of the circle marker marks the amount of documents mentioned in them - should this be kept or changed? The 1 document circle marker is too small I think, it's hard to click on it

**Comment by kisram** [comment]
true, but on the detail page there's actually no need to click the marker, nothing really happens if you do, because the pop-up is already open when you open the page
