### ISSUE TITLE
start page image shrinking

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#203]
![image](https://github.com/user-attachments/assets/a66a5841-7753-40bc-a751-f7b75ab776ff)

When minimizing the screen two images do not fill out the card
all cards behave as if they are hovered upon

is this (point 1 or 2 or both) something we should bother about?

**Comment by csae8092** [comment]
IMHO we should not bother

**Comment by kisram** [comment]
the cards behaving the same as after hovering below a certain screen size is intended behaviour, it's set to a width of 576px

**Comment by rausch-supola** [comment]
I uploaded broader images. Also fixed the issue, that the second word of "Grocery Categories" moves into the next row is not visible while shrinking. And changed the order of the cards so that everything concerning groceries is in one row
