### ISSUE TITLE
Make the documents column scrollable

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#21]
Scrollable documents column for Districts, Neighbourhoods, Persons, Categories of Goods based on "Goods"

**Comment by csae8092** [comment]
this applies actually for all columns with many data entries, e.g. the "goods" column in https://grocerist.github.io/grocerist-app/documents.html

**Comment by kisram** [comment]
> this applies actually for all columns with many data entries, e.g. the "goods" column in https://grocerist.github.io/grocerist-app/documents.html

Noted, will add those as well

**Comment by kisram** [comment]
Doesn't seem to be a simple copy&paste issue, because the table ends up empty after using the get_scrollable_cell as a formatter

**Comment by kisram** [comment]
> Doesn't seem to be a simple copy&paste issue, because the table ends up empty after using the get_scrollable_cell as a formatter

Figured it out, forgot to include a reference to the tabulator template in the other templates
