### ISSUE TITLE
check name of lat/long columns

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#22]
I recently renamed the latitude/longitute columns in baserow to lat/long which for sure might break some of the existing code;
* please check the baserow tables for consistent naming of those columns
* update the code base accordingly

**Comment by kisram** [comment]
changed columns in documents table to lat/long, the rest was already named accordingly

**Comment by kisram** [comment]
Adjusted code for Neighbourhoods, Documents doesn't seem to be using the lat/long columns in any code (yet)
