### ISSUE TITLE
update images on index page

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#237]
We received the rest of the images for the index page, including a new one for locations
Next step: think about adjusting the colours

**Comment by rausch-supola** [comment]
I would go maybe for something blueish or reddish (according to the pictures below)
![image](https://github.com/user-attachments/assets/cdf63fe6-693d-449d-a9f4-233d2d3d0102)

**Comment by rausch-supola** [comment]
maybe a bit too cold? 

![Screenshot from 2024-11-04 12-27-55](https://github.com/user-attachments/assets/ed9494e3-f65e-41a2-bced-974ec01145d1)

**Comment by rausch-supola** [comment]
Hm, it seems you have to give credit, a link to the license and say if you have made changes
