### ISSUE TITLE
interactive map

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#28]
link map with tabulator like in https://nestroyca.acdh-dev.oeaw.ac.at/nestroyvienna/

map should go to all list views for classes with coordinates (districts, neighbourhoods, karies), but start with districts

**Comment by kisram** [comment]
Adjusting the script for our data has proven to be a bit complicated: we just use markers, not circles indicating frequency, we have a lot of entries that don't have coordinates, no layers (at least not at this point), the data displayed in the table is quite different and the whole process of getting the json files was also different. It works now, just some cosmetics left (shadows are still visible after the marker becomes invisible, map focus when no markers are visible etc.)

**Comment by csae8092** [comment]
well, just checked and looks good enough for now; please feel free to merge your code into the main branch, but please make table and map the same height before
thank your!!!

**Comment by kisram** [comment]
I already did that yesterday, just haven't commited it yet because I was trying to fix the clicking after filtering issue
