### ISSUE TITLE
link to listview from detail view

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#35]
provide link from a detail view back to the listview, e.g. from 
https://grocerist.github.io/grocerist-app/document__4.html some icon next to the the page's h1 with a link back to https://grocerist.github.io/grocerist-app/documents.html

e.g. https://icons.getbootstrap.com/icons/chevron-up/

**Comment by kisram** [comment]
We were also talking about how it might make more sense to also be able to navigate "up" to the top from the listview
