### ISSUE TITLE
missing items in tables

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#51]
see e.g. https://grocerist.github.io/grocerist-app/karyes.html

only three rows are displayed although in baserow we have 22 rows (https://baserow.acdh-dev.oeaw.ac.at/database/275/table/1520/5680)

please check the other map/table views as well

**Comment by kisram** [comment]
I see all 22 rows (15 on the first page and the rest on the second)

**Comment by kisram** [comment]
just tried on all browsers and it looks fine, where did you have this issue?

**Comment by csae8092** [comment]
looks like some caching issue on my side; sorry for the hassle
