### ISSUE TITLE
combine tables with Highcharts

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#73]
Start with persons, make a chart that is responsive to filtering like the maps in Districts/Mahalles/Karyes

**Comment by kisram** [comment]
Not sure what to do with multiple districts for one person, do I just combine them like for persons or count them separately?
<img width="211" alt="image" src="https://github.com/grocerist/grocerist-app/assets/98097410/9d4a160a-bbf8-431e-afba-5d3ed045cd36">

**Comment by csae8092** [comment]
I'd try first to count them seperately

**Comment by kisram** [comment]
I just realized that in that case the district chart should be a bar chart...
Important question: the charts react to filtering now, but should the table also reactto clicks on the chart? Like if you click on a particular religion or district in the chart, and the table is filtered accordingly? @csae8092

**Comment by csae8092** [comment]
> this would be very nice indeed
