### ISSUE TITLE
updated gh-workflows actions

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#76]
our gh-workflows are using (soon to be) deprecated actions. therefore we receive warnings like
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, stefanzweifel/git-auto-commit-action@v4, peaceiris/actions-gh-pages@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

please have a look into those actions, see if there are more recent versions available and if so, update those accordingly

* e.g. check here https://github.com/grocerist/grocerist-app/blob/main/.github/workflows/build.yml#L34
* google for stefanzweifel/git-auto-commit-action@v4 (you should land somewhere like here https://github.com/stefanzweifel/git-auto-commit-action
* check in the readme for the latest version, e.g. in the code example
* if there is a newer version (spoiler, there is) please adapt our workflow file accordingly

**Comment by kisram** [comment]
peaceiris/actions-gh-pages are working on updating to Node 20: https://github.com/peaceiris/actions-gh-pages/issues/1062
