### ISSUE TITLE
location page

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#99]
There is no need for separate mahalle, karye, district pages, but there should be one location page with filtering options

**Comment by kisram** [comment]
- [ ] adjust make_geojson.py so all location jsons will be combined into one geojson we can use for the location site
- [ ] make necessary adjustments to templates (delete separate location templates, adjust index page)

**Comment by kisram** [comment]
@csae8092 @rausch-supola  Until now we had two marker colours based on the active layer (documents / persons), but it would probably make sense to change that to colours based on location type?
